# Generated by Django 4.1.7 on 2025-06-23 17:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'app_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='檔案名稱')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='檔案雜湊值')),
                ('file_size', models.IntegerField(verbose_name='檔案大小（bytes）')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('file_type', models.CharField(choices=[('green_bean', '生豆入庫記錄'), ('raw_material', '原料倉管理'), ('monthly_summary', '月度統計')], max_length=50, verbose_name='檔案類型')),
                ('records_count', models.IntegerField(default=0, verbose_name='記錄數量')),
                ('status', models.CharField(choices=[('pending', '處理中'), ('success', '成功'), ('failed', '失敗'), ('duplicate', '重複檔案')], default='pending', max_length=20, verbose_name='處理狀態')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='錯誤訊息')),
                ('created_record_ids', models.JSONField(blank=True, default=list, verbose_name='創建的記錄ID列表')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '檔案上傳記錄',
                'verbose_name_plural': '檔案上傳記錄',
                'db_table': 'app_file_upload_record',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='GreenBeanInboundRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='異常')),
                ('record_time', models.DateTimeField(blank=True, null=True, verbose_name='記錄時間')),
                ('order_number', models.CharField(default='', max_length=50, verbose_name='單號')),
                ('roasted_item_sequence', models.IntegerField(blank=True, null=True, verbose_name='炒豆項次')),
                ('green_bean_item_sequence', models.IntegerField(blank=True, null=True, verbose_name='生豆項次')),
                ('batch_sequence', models.IntegerField(blank=True, null=True, verbose_name='波次')),
                ('execution_status', models.CharField(blank=True, default='', max_length=20, verbose_name='執行狀態')),
                ('green_bean_batch_number', models.CharField(blank=True, default='', max_length=50, verbose_name='生豆批號')),
                ('green_bean_code', models.CharField(blank=True, default='', max_length=50, verbose_name='生豆料號')),
                ('green_bean_name', models.CharField(blank=True, default='', max_length=100, verbose_name='生豆名稱')),
                ('green_bean_storage_silo', models.CharField(blank=True, default='', max_length=50, verbose_name='生豆入庫筒倉')),
                ('bag_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='一袋重量(kg)')),
                ('input_bag_count', models.IntegerField(blank=True, null=True, verbose_name='投入袋數')),
                ('required_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='需求重量(kg)')),
                ('measured_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='生豆量測重量(kg)')),
                ('manual_input_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='手動投入重量(kg)')),
                ('work_start_time', models.DateTimeField(blank=True, null=True, verbose_name='作業開始時間')),
                ('work_end_time', models.DateTimeField(blank=True, null=True, verbose_name='作業結束時間')),
                ('work_duration', models.CharField(blank=True, max_length=20, verbose_name='作業時間')),
                ('ico_code', models.CharField(blank=True, max_length=50, verbose_name='ICO')),
                ('remark', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '生豆入庫記錄',
                'verbose_name_plural': '生豆入庫記錄',
                'db_table': 'app_green_bean_inbound_record',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialMonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='年度')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_inventory_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='總庫存價值')),
                ('total_incoming_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總進貨量')),
                ('total_outgoing_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總出貨量')),
                ('total_current_inventory', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='總當前庫存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '原料月度統計',
                'verbose_name_plural': '原料月度統計',
                'db_table': 'app_raw_material_monthly_summary',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialWarehouseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='品號')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='品名')),
                ('factory_batch_number', models.CharField(blank=True, max_length=100, verbose_name='工廠批號')),
                ('international_batch_number', models.CharField(blank=True, max_length=100, verbose_name='國際批號')),
                ('standard_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='標準重(kg)')),
                ('previous_month_inventory', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='上月庫存')),
                ('incoming_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='進貨')),
                ('outgoing_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='領用')),
                ('current_inventory', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='當前庫存')),
                ('pending_processing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='待處理')),
                ('opened_quality_external_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='開袋+品管+外賣剩下')),
                ('external_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='外賣')),
                ('record_date', models.DateField(blank=True, null=True, verbose_name='記錄日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '原料倉進出記錄',
                'verbose_name_plural': '原料倉進出記錄',
                'db_table': 'app_raw_material_warehouse_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(help_text='輸入範例：0900123456', max_length=10, validators=[django.core.validators.RegexValidator(message='請依照格式輸入', regex='^09\\d{8}$')], verbose_name='聯絡電話')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '管理者',
                'verbose_name_plural': '管理者',
                'db_table': 'app_adminuser',
            },
        ),
        migrations.CreateModel(
            name='UploadRecordRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('green_bean', '生豆入庫記錄'), ('raw_material', '原料倉管理'), ('monthly_summary', '月度統計')], max_length=50, verbose_name='資料類型')),
                ('object_id', models.UUIDField(verbose_name='關聯記錄ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('upload_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fileuploadrecord', verbose_name='上傳記錄')),
            ],
            options={
                'verbose_name': '上傳記錄關聯',
                'verbose_name_plural': '上傳記錄關聯',
                'db_table': 'app_upload_record_relation',
                'unique_together': {('upload_record', 'content_type', 'object_id')},
            },
        ),
    ]
