# Generated by Django 4.1.7 on 2025-06-24 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='功能代碼')),
                ('name', models.CharField(max_length=100, verbose_name='功能名稱')),
                ('description', models.TextField(blank=True, verbose_name='功能描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '系統功能',
                'verbose_name_plural': '系統功能',
                'db_table': 'app_system_feature',
            },
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': '管理員', 'verbose_name_plural': '管理員'},
        ),
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(max_length=50, verbose_name='功能代碼')),
                ('feature_name', models.CharField(max_length=100, verbose_name='功能名稱')),
                ('permission_type', models.CharField(choices=[('view', '瀏覽'), ('edit', '編輯')], max_length=10, verbose_name='權限類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '功能權限',
                'verbose_name_plural': '功能權限',
                'db_table': 'app_feature_permission',
                'unique_together': {('user', 'feature_code')},
            },
        ),
    ]
