# Generated by Django 4.1.7 on 2025-07-06 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0002_systemfeature_alter_adminuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('delete', '刪除'), ('upload', '上傳'), ('export', '匯出'), ('login', '登入'), ('logout', '登出')], max_length=20, verbose_name='操作類型')),
                ('description', models.CharField(max_length=255, verbose_name='操作描述')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用戶代理')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='詳細信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶活動記錄',
                'verbose_name_plural': '用戶活動記錄',
                'db_table': 'app_user_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
