# Generated by Django 4.1.7 on 2025-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('create', '新增'), ('update', '更新'), ('delete', '刪除'), ('upload', '上傳'), ('delete_upload_record', '刪除上傳記錄'), ('batch_delete', '批量刪除'), ('export', '匯出'), ('login', '登入'), ('logout', '登出')], max_length=20, verbose_name='操作類型'),
        ),
    ]
