# Generated by Django 4.1.7 on 2025-07-31 02:27

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0005_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPGroup',
            fields=[
            ],
            options={
                'verbose_name': '群組',
                'verbose_name_plural': '群組管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ERPPermission',
            fields=[
            ],
            options={
                'verbose_name': '權限',
                'verbose_name_plural': '權限管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterialwarehouserecord',
            name='is_abnormal',
            field=models.BooleanField(default=False, verbose_name='異常'),
        ),
    ]
