# Generated by Django 4.1.7 on 2025-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_erpgroup_erppermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialwarehouserecord',
            name='is_abnormal',
        ),
        migrations.AddField(
            model_name='rawmaterialwarehouserecord',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, help_text='儲存所有動態欄位，如日期_入庫、日期_領用等', verbose_name='動態欄位資料'),
        ),
    ]
