# Generated by Django 4.1.7 on 2025-07-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_rawmaterialwarehouserecord_is_abnormal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialwarehouserecord',
            name='external_sales',
        ),
        migrations.RemoveField(
            model_name='rawmaterialwarehouserecord',
            name='opened_quality_external_remaining',
        ),
    ]
