# Generated by Django 4.1.7 on 2025-07-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_rawmaterialwarehouserecord_external_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20, verbose_name='日期')),
                ('field_name', models.CharField(max_length=50, verbose_name='欄位名稱')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='數值')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields_set', to='app.rawmaterialwarehouserecord')),
            ],
            options={
                'verbose_name': '動態欄位',
                'verbose_name_plural': '動態欄位',
            },
        ),
    ]
