# Generated by Django 4.1.7 on 2025-08-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_rawmaterialwarehouserecord_external_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialwarehouserecord',
            name='pending_processing',
        ),
    ]
