# Generated by Django 4.1.7 on 2025-08-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rawmaterialdynamicfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-created_at'], 'permissions': [('view_user_activities', '查看用戶活動記錄')], 'verbose_name': '用戶活動記錄', 'verbose_name_plural': '用戶活動記錄'},
        ),
        migrations.RemoveField(
            model_name='rawmaterialwarehouserecord',
            name='pending_processing',
        ),
        migrations.DeleteModel(
            name='RawMaterialDynamicField',
        ),
    ]
