# Generated by Django 4.1.7 on 2025-08-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_useractivitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-created_at'], 'verbose_name': '用戶活動記錄', 'verbose_name_plural': '用戶活動記錄'},
        ),
    ]
