# Generated by Django 4.1.7 on 2025-08-28 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_useractivitylog_options'),
    ]

    operations = [
        # 手動新增 CreateModel 操作，用於補全 0001_initial.py 中缺少的模型
        # 注意：這裡只是一個範例，需要根據您 models.py 中實際的欄位來填寫
        
        migrations.CreateModel(
            name='RawMaterialDynamicField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='欄位名稱')),
                ('label', models.CharField(max_length=100, verbose_name='顯示名稱')),
                ('field_type', models.CharField(choices=[('date', '日期'), ('number', '數字'), ('text', '文字')], default='text', max_length=20, verbose_name='欄位類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '原料倉動態欄位',
                'verbose_name_plural': '原料倉動態欄位',
                'db_table': 'app_raw_material_dynamic_field',
                'ordering': ['name'],
            },
        ),
    ]
